### ISSUE TITLE
Investigate using `eipw` to check PIPs in pull requests

### ISSUE THREAD

**Issue by SamWilsn** [maticnetwork/Polygon-Improvement-Proposals#117]
Hey!

I'm the author of [`eipw`](https://github.com/ethereum/eipw), the tool we use to check EIPs for consistency in pull requests. `eipw` is a markdown lint tool, and is **not** the bot that handles merging and permissions for EIPs.

If you folks are interested, we could investigate whether `eipw` would be a useful tool to integrate with this repository. Personally, I'd love to see it get adopted by other projects, and maybe even increase the [bus factor](https://en.wikipedia.org/wiki/Bus_factor) above one.

If you aren't familiar with `eipw`, it's the tool that generates these annotations:

![image](https://github.com/maticnetwork/Polygon-Improvement-Proposals/assets/57262657/ddbe5510-f5a8-47e2-9f73-aa623c709dad)

It can be configured using TOML, like so:

```toml
[lints.markdown-re-pip-dash]
kind = "markdown-regex"
mode = "excludes"
pattern = '(?i)pip[\s]*[0-9]+'
message = "proposals must be referenced with the form `PIP-N` (not `PIPN` or `PIP N`)"
```
